### ISSUE TITLE
Fall 2024: Features and Bug Fixes

### ISSUE THREAD

**Issue by Thompson632** [What-Should-I-Eat/WSIE#191]
# Features and Bug Fixes for Fall 24

Bug fixes should take first priority (and help new team members get familiar with code base), but don't worry about all of the bug fixes right at the beginning.

All features are in order of priority per category. I assigned a story point value for each so our new members can get a feel for the difficulty, but change those or ignore if they don't fit. Feel free to skip around to different categories based on skill/interest. 

## Bug Fixes
- [ ] Fix font to be the same across all browsers. Currently, Safari renders our specified CSS font and Chrome renders Times New Roman. {1 pt}
- [ ] Show URL at the top of the browser instead of the IP address after web page loads {2 pts - might have to do some research}
- [ ] Fix issue where user create recipe is not updating on save {3 pts}

## User Experience Features
- [ ] Amin page: create admin screen to manually process/screen user created recipe requests (trigger email upon approval/denial?) {5 pts}
- [ ] Like/favorite counter on user created recipes  {1 pt}
- [ ] Toggle to show/hide user created recipes {2 pts}
- [ ] Allow user to remove self-published recipes {2 pts}
- [ ] Tag cuisine types in user created recipes {2 pts}
- [ ] Add button to user created recipes that asks user to show user name. Display username of creator in user created recipes if this button is checked or "Created by Anonymous" if not checked {2 pts}

## CI/CD / Architecture Features
- [ ] Cron job for database backup across VM restarts {5 pts}
- [ ] Cache data such as my recipes so we don't need to fetch each time (this will make loading faster) {3 pts}
- [ ] Allow auto-login after successful verification with server cookies {5 pts}

## Backlog Features 
- [ ] Continue with ad space - Torie will do some research on ad enablement if you get to this feature {? pts}
- [ ] Refactor legacy tests for new client. When complete, remove all legacy source {13 pts}
- [ ] Update client/server so you can run standalone from docker. CORS issue between ports and requests. Need to handle the additional port for CORS (client 3000, server 3001). {8 pts}
- [ ] Find different CI/CD solution than GCP VM. This could be Azure, another GCP service, etc. {13 pts}
- [ ] Create space for users to review/comment on user created recipes. This should utilize an API that screens for profanity, etc. {8 pts}

Add on to these as you see fit throughout the quarter.

**Comment by torieee** [comment]
Torie's quick notes from presentation (will update later):

Bug fixes
- Fix font to be the same across all browsers
- Fix the update recipe bug where it does not update
- Get url to not be the IP address
- Catch data (so we don’t fetch each time)
- Keep track of number of favorites
- Tag cuisine types in user created recipes


Features next quarter
- Ad enablement
- HTTPS instead of HTTP
- Toggle on and off user created recipes
- Hosting not on GCP / CICD solution
- Admin account (role in db?)
- Reviews on the recipes?
